# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobuf_pb2 as protobuf__pb2


class MusicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/mypackage.MusicService/ListUsers',
                request_serializer=protobuf__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=protobuf__pb2.ListUsersResponse.FromString,
                )
        self.ListSongs = channel.unary_unary(
                '/mypackage.MusicService/ListSongs',
                request_serializer=protobuf__pb2.ListSongsRequest.SerializeToString,
                response_deserializer=protobuf__pb2.ListSongsResponse.FromString,
                )
        self.ListUserPlaylists = channel.unary_unary(
                '/mypackage.MusicService/ListUserPlaylists',
                request_serializer=protobuf__pb2.ListUserPlaylistsRequest.SerializeToString,
                response_deserializer=protobuf__pb2.ListUserPlaylistsResponse.FromString,
                )
        self.ListPlaylistSongs = channel.unary_unary(
                '/mypackage.MusicService/ListPlaylistSongs',
                request_serializer=protobuf__pb2.ListPlaylistSongsRequest.SerializeToString,
                response_deserializer=protobuf__pb2.ListPlaylistSongsResponse.FromString,
                )
        self.ListPlaylistsBySong = channel.unary_unary(
                '/mypackage.MusicService/ListPlaylistsBySong',
                request_serializer=protobuf__pb2.ListPlaylistsBySongRequest.SerializeToString,
                response_deserializer=protobuf__pb2.ListPlaylistsBySongResponse.FromString,
                )


class MusicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylistSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylistsBySong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=protobuf__pb2.ListUsersRequest.FromString,
                    response_serializer=protobuf__pb2.ListUsersResponse.SerializeToString,
            ),
            'ListSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSongs,
                    request_deserializer=protobuf__pb2.ListSongsRequest.FromString,
                    response_serializer=protobuf__pb2.ListSongsResponse.SerializeToString,
            ),
            'ListUserPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserPlaylists,
                    request_deserializer=protobuf__pb2.ListUserPlaylistsRequest.FromString,
                    response_serializer=protobuf__pb2.ListUserPlaylistsResponse.SerializeToString,
            ),
            'ListPlaylistSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylistSongs,
                    request_deserializer=protobuf__pb2.ListPlaylistSongsRequest.FromString,
                    response_serializer=protobuf__pb2.ListPlaylistSongsResponse.SerializeToString,
            ),
            'ListPlaylistsBySong': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylistsBySong,
                    request_deserializer=protobuf__pb2.ListPlaylistsBySongRequest.FromString,
                    response_serializer=protobuf__pb2.ListPlaylistsBySongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MusicService/ListUsers',
            protobuf__pb2.ListUsersRequest.SerializeToString,
            protobuf__pb2.ListUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MusicService/ListSongs',
            protobuf__pb2.ListSongsRequest.SerializeToString,
            protobuf__pb2.ListSongsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MusicService/ListUserPlaylists',
            protobuf__pb2.ListUserPlaylistsRequest.SerializeToString,
            protobuf__pb2.ListUserPlaylistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPlaylistSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MusicService/ListPlaylistSongs',
            protobuf__pb2.ListPlaylistSongsRequest.SerializeToString,
            protobuf__pb2.ListPlaylistSongsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPlaylistsBySong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.MusicService/ListPlaylistsBySong',
            protobuf__pb2.ListPlaylistsBySongRequest.SerializeToString,
            protobuf__pb2.ListPlaylistsBySongResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
