# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\x12\tmypackage\"\x12\n\x10ListUsersRequest\"3\n\x11ListUsersResponse\x12\x1e\n\x05users\x18\x01 \x03(\x0b\x32\x0f.mypackage.User\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x12\n\x10ListSongsRequest\"3\n\x11ListSongsResponse\x12\x1e\n\x05songs\x18\x01 \x03(\x0b\x32\x0f.mypackage.Song\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"+\n\x18ListUserPlaylistsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"C\n\x19ListUserPlaylistsResponse\x12&\n\tplaylists\x18\x01 \x03(\x0b\x32\x13.mypackage.Playlist\"5\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"/\n\x18ListPlaylistSongsRequest\x12\x13\n\x0bplaylist_id\x18\x01 \x01(\x05\";\n\x19ListPlaylistSongsResponse\x12\x1e\n\x05songs\x18\x01 \x03(\x0b\x32\x0f.mypackage.Song\"-\n\x1aListPlaylistsBySongRequest\x12\x0f\n\x07song_id\x18\x01 \x01(\x05\"E\n\x1bListPlaylistsBySongResponse\x12&\n\tplaylists\x18\x01 \x03(\x0b\x32\x13.mypackage.Playlist2\xce\x03\n\x0cMusicService\x12H\n\tListUsers\x12\x1b.mypackage.ListUsersRequest\x1a\x1c.mypackage.ListUsersResponse\"\x00\x12H\n\tListSongs\x12\x1b.mypackage.ListSongsRequest\x1a\x1c.mypackage.ListSongsResponse\"\x00\x12`\n\x11ListUserPlaylists\x12#.mypackage.ListUserPlaylistsRequest\x1a$.mypackage.ListUserPlaylistsResponse\"\x00\x12`\n\x11ListPlaylistSongs\x12#.mypackage.ListPlaylistSongsRequest\x1a$.mypackage.ListPlaylistSongsResponse\"\x00\x12\x66\n\x13ListPlaylistsBySong\x12%.mypackage.ListPlaylistsBySongRequest\x1a&.mypackage.ListPlaylistsBySongResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTUSERSREQUEST._serialized_start=29
  _LISTUSERSREQUEST._serialized_end=47
  _LISTUSERSRESPONSE._serialized_start=49
  _LISTUSERSRESPONSE._serialized_end=100
  _USER._serialized_start=102
  _USER._serialized_end=147
  _LISTSONGSREQUEST._serialized_start=149
  _LISTSONGSREQUEST._serialized_end=167
  _LISTSONGSRESPONSE._serialized_start=169
  _LISTSONGSRESPONSE._serialized_end=220
  _SONG._serialized_start=222
  _SONG._serialized_end=270
  _LISTUSERPLAYLISTSREQUEST._serialized_start=272
  _LISTUSERPLAYLISTSREQUEST._serialized_end=315
  _LISTUSERPLAYLISTSRESPONSE._serialized_start=317
  _LISTUSERPLAYLISTSRESPONSE._serialized_end=384
  _PLAYLIST._serialized_start=386
  _PLAYLIST._serialized_end=439
  _LISTPLAYLISTSONGSREQUEST._serialized_start=441
  _LISTPLAYLISTSONGSREQUEST._serialized_end=488
  _LISTPLAYLISTSONGSRESPONSE._serialized_start=490
  _LISTPLAYLISTSONGSRESPONSE._serialized_end=549
  _LISTPLAYLISTSBYSONGREQUEST._serialized_start=551
  _LISTPLAYLISTSBYSONGREQUEST._serialized_end=596
  _LISTPLAYLISTSBYSONGRESPONSE._serialized_start=598
  _LISTPLAYLISTSBYSONGRESPONSE._serialized_end=667
  _MUSICSERVICE._serialized_start=670
  _MUSICSERVICE._serialized_end=1132
# @@protoc_insertion_point(module_scope)
